### ISSUE TITLE
Inbound and outbound codecs selection

### ISSUE THREAD

**Issue by kalmik** [jchavanton/voip_patrol#11]
The users should be able to select which codecs may be selected on a SIP dialog

**Comment by kalmik** [comment]
Hi @jchavanton, I have created this issue to improve that feature we talked last week at ClueCon and can discuss the feature goals.

**Comment by jchavanton** [comment]
Hi, yes, this feature is required, sorry for the delay, I need to make sure I receive notifications.

**Comment by jchavanton** [comment]
I did set email notifications, I am planning to do it soon but if you do it before of course it would be appreciated !

**Comment by jchavanton** [comment]
done.

```
<config><actions>
    <action type="codec" disable="all"/>
    <action type="codec" enable="pcma" priority="250"/>
    <action type="codec" enable="gsm" priority="249"/>
    <action type="codec" enable="pcmu" priority="248"/>

    <action type="call" ...
````
