### ISSUE TITLE
responce_delay is blocking option in accept

### ISSUE THREAD

**Issue by igorolhovskiy** [jchavanton/voip_patrol#32]
Hello!

As of now, implementation of `responce_delay` is done via `pj_thread_sleep()` which is blocking operation on all scenario running.
I've made a rework of it, but also made `responce_delay` parameter to be in seconds to be coherent with other duration parameters. 
I can prepare an merge-request for this, but before I have a question - what is a best idea, to keep `responce_delay` in miliseconds or change the default behavior of this parameter (to make it coherent), but here we can  loose precision in setting this parameter.

**Comment by jchavanton** [comment]
Nice finding, I would say response delay in ms may be left in ms at the cost of small lack of coherence.

**Comment by igorolhovskiy** [comment]
Resolved with https://github.com/jchavanton/voip_patrol/pull/33
