### ISSUE TITLE
Make realm on register and call optional parameter

### ISSUE THREAD

**Issue by igorolhovskiy** [jchavanton/voip_patrol#35]
Julien,
I can prepare a patch that will take `realm = "*"` if it's not specified. 
Let me know if it's ok.
Ihor

**Comment by jchavanton** [comment]
Hi, I do not see why not, as long a you make a few tests, maybe you can post the test you have made ?

**Comment by igorolhovskiy** [comment]
I'll try to post traces, it was tested with sever, that is sending different realm based on username.
But selecting default `*` is based on
https://github.com/pjsip/pjproject/blob/863629bc65d68518d85cf94758725da3042c2445/pjsip/include/pjsip/sip_auth.h#L108
and various examples in pjsip like
https://github.com/pjsip/pjproject/blob/863629bc65d68518d85cf94758725da3042c2445/pjsip-apps/src/pjsua2/ios-swift-pjsua2/ios-swift-pjsua2/PJSua2/CustomPJSUA2.cpp#L212

**Comment by jchavanton** [comment]
looks good  !

**Comment by igorolhovskiy** [comment]
Julien,

Sorry for late reply, you really have the point, it's not really mandatory feature as voip_patrol is not that dynamic and having this field mandatory can be also a sort of security add.
For showing you the tests, some of them can be found at https://github.com/igorolhovskiy/volts/tree/main/vp_scenarios (not all of em using this feature)

Cheers,
Ihor

**Comment by jchavanton** [comment]
Hi Igor, I think you are right the the realm should be set to work by default, I just made the modification to simplify things for everyone.
