### ISSUE TITLE
Multi account support

### ISSUE THREAD

**Issue by supapo** [jchavanton/voip_patrol#47]
Is it possible to have support for multiple accounts like `sipp`?
this means using the same XML but with dictionary variables from csv files and the XML will repeat for each line in the dictionary.
[SIPp ref
](https://sipp.sourceforge.net/doc/reference.html#Injecting+values+from+an+external+CSV+during+calls)

**Comment by jchavanton** [comment]
Just to be clear, multiple accounts are already supported.

**Comment by supapo** [comment]
Thank you @jchavanton, can you guide me to the multi-account doc?

**Comment by jchavanton** [comment]
I added a section in the documentation
https://github.com/jchavanton/voip_patrol?tab=readme-ov-file#using-multiple-accounts
