### ISSUE TITLE
not able to have output in different file.

### ISSUE THREAD

**Issue by surendratiwari3** [jchavanton/voip_patrol#6]
-o argument is not working

**Comment by jchavanton** [comment]
Hi this was fix few days ago.

**Comment by jchavanton** [comment]
6 days ago "fix output filename param"

**Comment by jchavanton** [comment]
you can reopen the issue if this is still not working 

Thanks for reporting

**Comment by surendratiwari3** [comment]
yeah, this is working after taking git pull from latest.
